### ISSUE TITLE
INITIAL_PUZZLES is not awaited in some functions

### ISSUE THREAD

**Issue by brian-xu** [qiaochloe/bph-site#128]
Causing a crash on Vercel.

On another note, is there a more efficient way to do this? Perhaps we can define an initial puzzle by inserting specific unlocks upon team registration.

**Comment by qiaochloe** [comment]
Good point, I was hesitant to insert unlocks during team registration because the hunt-writers might want to change the initial puzzle after team registration and before the hunt starts. 

But this specific function is for maintaining compatibility between everyone's (personal) databases, which might have different puzzles.
